import { FrameworkOverview, OwaspTop10Entry } from './types';

const OFFICIAL_ASI_PAGE = 'https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications-for-2026/';
const INCIDENT_TRACKER = 'https://github.com/OWASP/www-project-top-10-for-large-language-model-applications/blob/main/initiatives/agent_security_initiative/ASI%20Agentic%20Exploits%20%26%20Incidents/ASI_Agentic_Exploits_Incidents.md';

export const AGENTIC_APPLICATIONS_OVERVIEW: FrameworkOverview = {
  edition: '2026 edition · published December 2025',
  scopeNote: 'The OWASP Top 10 for Agentic Applications describes the highest-impact security risks created when AI systems can plan, remember, call tools, delegate to other agents, and act with limited supervision. It is the application- and workflow-level companion to the Agentic Skills Top 10: ASI follows autonomous behavior across the whole system, while AST examines the reusable skill packages that supply instructions, code, metadata, and resources.',
  severityNote: 'The whitepaper does not publish a severity ranking among ASI01-ASI10. Prioritize findings with the deployment context, blast radius, autonomy, privileges, memory use, human oversight, and AIVSS rather than treating the list order as a score.',
  riskGroups: [
    { title: 'Intent & authority', entries: ['ASI01', 'ASI02', 'ASI03'], description: 'Manipulated goals, legitimate tools used unsafely, and abuse of agent identities, credentials, delegation, or inherited privileges.' },
    { title: 'Components & execution', entries: ['ASI04', 'ASI05'], description: 'Compromised runtime dependencies and agent-driven execution of unsafe code, commands, packages, or serialized content.' },
    { title: 'State & coordination', entries: ['ASI06', 'ASI07', 'ASI08'], description: 'Persistent context corruption, insecure live agent messages, and faults that fan out across agents, tenants, or workflows.' },
    { title: 'Human & behavioral integrity', entries: ['ASI09', 'ASI10'], description: 'Manipulation of human trust and agents whose behavior drifts, schemes, colludes, self-replicates, or otherwise escapes governance.' },
  ],
  terminology: [
    { term: 'Agentic application', definition: 'A system in which one or more AI agents can plan, retain state, use tools, communicate, delegate, and execute actions toward a goal.' },
    { term: 'Least Agency', definition: 'Grant the minimum autonomy, tools, data, time, delegation depth, and operational scope needed for a task, with explicit checkpoints for consequential actions.' },
    { term: 'Intent binding', definition: 'Bind identity, credentials, authorization, tool calls, and messages to the user-approved purpose, audience, resource, task, and session so permission cannot silently drift.' },
    { term: 'Memory and context', definition: 'Conversation state, summaries, embeddings, RAG stores, long-term memory, and other retained or retrieved information reused during later reasoning.' },
    { term: 'MCP / A2A', definition: 'Protocols and ecosystems through which agents discover capabilities, call tools, and coordinate. Their descriptors, registries, identities, messages, and version negotiation are part of the application attack surface.' },
    { term: 'AIVSS', definition: 'OWASP Agentic AI Vulnerability Scoring System. Its autonomy, memory, context, behavioral-integrity, operational-security, and compliance factors help prioritize concrete findings.' },
  ],
  triageSteps: [
    'Identify the initial control failure: goal manipulation (ASI01), tool use within granted scope (ASI02), identity or authorization abuse (ASI03), supply-chain compromise (ASI04), code execution (ASI05), stored-context corruption (ASI06), or live-message compromise (ASI07).',
    'Use ASI08 only when an initial fault propagates or amplifies beyond its origin across agents, sessions, tenants, tools, or workflows; record the originating ASI as the root cause.',
    'Use ASI09 when harm depends on misleading or over-trusting a person; use ASI10 when the central issue is sustained behavioral divergence or loss of governance after drift begins.',
    'Record overlapping LLM, AST, MCP, NHI, and Agentic Threats & Mitigations mappings as contributing layers rather than forcing one label to describe the entire chain.',
    'Prioritize by effective autonomy, reachable data and tools, credential lifetime, propagation speed, reversibility, human oversight, and the maximum credible blast radius.',
  ],
  resources: [
    { title: 'Official OWASP ASI 2026 resource page', url: OFFICIAL_ASI_PAGE },
    { title: 'ASI exploits and incidents tracker', url: INCIDENT_TRACKER },
    { title: 'OWASP Agentic Skills Top 10', url: 'https://owasp.org/www-project-agentic-skills-top-10/' },
    { title: 'OWASP GenAI Security Project', url: 'https://genai.owasp.org/' },
  ],
};

const APPLICATION_ENTRIES: OwaspTop10Entry[] = [
  {
    id: 'ASI01',
    title: 'Agent Goal Hijack',
    description: 'An attacker changes an agent’s objective, decision path, or multi-step behavior through direct or indirect prompt injection, deceptive tool output, forged agent messages, poisoned external data, or manipulated business context. Unlike a one-response prompt-injection finding, goal hijack follows the effect into planning, delegation, tool selection, and autonomous action.',
    whyUnique: 'ASI01 is direct manipulation of the active goal or its interpretation. Persistent corruption belongs primarily to ASI06, misuse of an otherwise accepted tool call to ASI02, and sustained autonomous behavioral divergence after the initiating compromise to ASI10.',
    commonRisks: [
      'Hidden instructions in websites, RAG chunks, documents, issue text, email, calendar invitations, Teams messages, or tool results are treated as authoritative task instructions.',
      'A malicious party changes constraints, success criteria, risk tolerance, recipients, destinations, or action order while leaving the high-level request apparently intact.',
      'Long-running or scheduled agents gradually lose the original goal, invariants, or approval boundary as context is summarized and refreshed.',
      'Business-process data such as invoices, vendor records, payment details, or customer requests carries instructions that redirect privileged actions.',
      'Cross-agent messages or delegated subtasks introduce a conflicting objective that the receiving agent cannot distinguish from the original user intent.',
    ],
    realWorldEvidence: [
      'EchoLeak showed that an email could indirectly prompt Microsoft 365 Copilot to expose confidential information without a user clicking the malicious content.',
      'Prompt injection against ChatGPT Operator demonstrated that hostile web content could steer a browser agent while it had access to authenticated pages.',
      'The Google Gemini Trifecta linked poisoned logs, search history, and browsing context to unintended actions and sensitive-data exposure across connected services.',
      'Public issue text has been used to hijack development agents and cause private repository contents to be disclosed across repository boundaries.',
    ],
    attackScenarios: [
      { title: 'Hidden retrieval instruction', description: 'A trusted knowledge result contains concealed text that replaces the research goal with collection and exfiltration of internal data.' },
      { title: 'Communication-channel injection', description: 'A crafted email, meeting invitation, chat message, or ticket tells an agent to ignore the original workflow and perform an attacker-selected action.' },
      { title: 'Payment redirection', description: 'A manipulated invoice or vendor record changes bank details and urgency cues, so a finance agent prepares or approves a fraudulent transfer.' },
      { title: 'Scheduled goal drift', description: 'A long-running agent repeatedly summarizes its state until the original constraints disappear and an unsafe optimization becomes the effective goal.' },
      { title: 'Cross-agent inception', description: 'A malicious document controls a research agent, whose apparently valid delegation then changes the objective of a more privileged executor.' },
    ],
    preventionStrategies: [
      'Treat every natural-language input outside the immutable policy boundary as untrusted data, including retrieval results, tool output, messages, documents, and peer-agent content.',
      'Apply Least Agency: minimize autonomy and privileges, and require explicit human approval for goal changes or high-impact, irreversible, financial, security, or external-facing actions.',
      'Lock system prompts, policy, workflow invariants, and configuration behind version control, signed releases, access control, and change review.',
      'Validate both user intent and agent intent before action. Bind a signed intent capsule to the stable goal identifier, allowed resources, audience, parameters, session, and expiry.',
      'Sanitize connected sources with content-disarm and reconstruction where appropriate, prompt-carrier detection, provenance, trust labels, and instruction/data separation.',
      'Log the baseline goal, invariants, plans, decisions, delegations, and tool calls; alert on goal drift, skipped controls, novel destinations, or unexplained workflow changes.',
      'Red-team indirect and cross-agent injection regularly, retain safe snapshots, support rollback, and include malicious-insider scenarios in governance and monitoring.',
    ],
    implementationNotes: [
      { title: 'Goal integrity record', content: 'Persist a stable goal ID, user-approved purpose, non-negotiable invariants, allowed side effects, approval requirements, and termination criteria outside model-controlled memory. Compare each plan and consequential action against this record.' },
      { title: 'Intent gate', content: 'Before execution, a policy decision point should compare the proposed action and arguments with the original user intent, current authorization, provenance, risk, and expected workflow. Fail closed when the relationship cannot be established.' },
    ],
    owaspMappings: ['LLM01:2025 Prompt Injection', 'LLM06:2025 Excessive Agency'],
    otherMappings: ['Agentic T6 Goal Manipulation', 'Agentic T7 Misaligned & Deceptive Behaviors', 'AIVSS: Agent Goal & Instruction Manipulation', 'NHI10 Human Use of NHI'],
    relatedRisks: [
      { id: 'ASI02', title: 'Tool Misuse and Exploitation', relationship: 'A hijacked goal commonly turns legitimate tool access into harmful action.' },
      { id: 'ASI06', title: 'Memory & Context Poisoning', relationship: 'Persistent poisoned context can change later goal interpretation.' },
      { id: 'ASI10', title: 'Rogue Agents', relationship: 'A hijack may initiate sustained behavioral divergence, but ASI10 describes the resulting loss of integrity.' },
    ],
    references: [
      { title: 'OWASP ASI exploits and incidents tracker', url: INCIDENT_TRACKER },
      { title: 'EchoLeak analysis', url: 'https://www.aim.security/lp/aim-labs-echoleak-blogpost' },
      { title: 'ChatGPT Operator prompt injection research', url: 'https://embracethered.com/blog/posts/2025/chatgpt-operator-prompt-injection-exploits/' },
    ],
  },
  {
    id: 'ASI02',
    title: 'Tool Misuse and Exploitation',
    description: 'An agent uses a legitimate tool in an unsafe, unintended, or adversary-controlled way while remaining inside the tool’s nominal authorization. Ambiguous instructions, unsafe delegation, prompt injection, poisoned tool descriptions, unchecked arguments, and excessive action loops can turn ordinary shell, database, browser, messaging, financial, or administrative functions into attack primitives.',
    whyUnique: 'ASI02 concerns unsafe use within available capability. If the agent obtains or inherits authority it should not have, classify ASI03; if arbitrary code or command execution is the core impact, classify ASI05; if the tool or dependency itself was malicious or compromised, classify ASI04.',
    commonRisks: [
      'Over-broad tools expose more operations, data, destinations, or parameters than the task requires.',
      'Agent-generated values are forwarded to shells, interpreters, SQL, file paths, browsers, or administrative APIs without schema, semantic, or destination validation.',
      'A browser or retrieval tool follows attacker-controlled content into authenticated or sensitive contexts.',
      'Retries, recursive delegation, or tool loops amplify cost, destructive actions, messages, requests, or resource use.',
      'Poisoned tool descriptions, deceptive names, and typosquatted capabilities cause the model to select an attacker-controlled function.',
      'Several individually approved tools are chained into an unapproved capability, such as reading internal CRM data and sending it externally.',
    ],
    realWorldEvidence: [
      'Tool poisoning research has shown that malicious MCP descriptions can manipulate agents before the user invokes the affected capability.',
      'A malicious Postmark-compatible MCP package silently added attacker-controlled BCC recipients while presenting itself as a normal email integration.',
      'The Google Gemini Trifecta and EchoLeak demonstrated how connected-service access can turn indirect instructions into unintended data access or disclosure.',
      'MCP Inspector and development-agent vulnerabilities have chained prompt injection or exposed control interfaces into operating-system command execution.',
    ],
    attackScenarios: [
      { title: 'Tool-interface poisoning', description: 'A hidden instruction in a capability description tells the agent to prefer a malicious tool or disclose data in its arguments.' },
      { title: 'Indirect injection to shell', description: 'Attacker-controlled web or document content is copied into a permitted shell command and changes its meaning.' },
      { title: 'Over-privileged refund API', description: 'A support agent turns a low-risk customer conversation into an unauthorized high-value refund because the tool has no transaction ceiling or approval gate.' },
      { title: 'Cross-tool exfiltration', description: 'The agent reads confidential CRM data with one approved tool and transmits it through another approved email or HTTP tool.' },
      { title: 'Approved-tool living-off-the-land', description: 'PowerShell, curl, ping, DNS, or an administrative utility is used for payload retrieval, evasion, or covert exfiltration even though each binary is allowed.' },
    ],
    preventionStrategies: [
      'Apply Least Agency and least privilege per tool: narrow operations, resources, data fields, destinations, rates, egress, transaction values, and invocation counts.',
      'Require per-action authorization, clear side-effect previews, dry-run where possible, and human approval for sensitive, irreversible, external, financial, or administrative operations.',
      'Run tools in isolated environments with restricted files, credentials, processes, network routes, and destination allowlists.',
      'Place a policy enforcement point between planning and execution that validates typed arguments, semantic intent, provenance, rates, destinations, and current authorization.',
      'Issue just-in-time, short-lived, session- and task-bound credentials instead of exposing standing shared secrets to the agent.',
      'Set tool budgets for time, tokens, retries, calls, spend, affected records, and delegation depth; stop safely when a budget or invariant is crossed.',
      'Use fully qualified tool names, pinned versions, signed descriptors, semantic-diff checks, and fail-closed behavior for ambiguous, substituted, or changed tools.',
      'Keep immutable invocation logs with proposed and executed arguments, identity, policy decision, outcome, and drift or anomaly signals.',
    ],
    implementationNotes: [
      { title: 'Capability firewall', content: 'Resolve the exact tool identity and version, validate a typed request, compare its effect with the approved task, enforce policy outside the model, and return a bounded structured result. Do not rely on the model to police its own action.' },
      { title: 'Composition analysis', content: 'Evaluate the effective capability of tool chains, not only individual calls. A read tool plus an outbound tool creates an exfiltration path even when neither is independently prohibited.' },
    ],
    owaspMappings: ['LLM06:2025 Excessive Agency'],
    otherMappings: ['Agentic T2 Tool Misuse', 'Agentic T4 Resource Overload', 'Agentic T16 Insecure Inter-Agent Protocol Abuse', 'AIVSS: Agentic AI Tool Misuse', 'NHI2 Secret Leakage', 'NHI5 Overprivileged NHI'],
    relatedRisks: [
      { id: 'ASI01', title: 'Agent Goal Hijack', relationship: 'Goal manipulation often supplies the malicious intent that drives tool misuse.' },
      { id: 'ASI03', title: 'Identity and Privilege Abuse', relationship: 'Privilege acquisition or confused-deputy behavior moves the finding from unsafe use to authority abuse.' },
      { id: 'ASI05', title: 'Unexpected Code Execution (RCE)', relationship: 'Unsafe shell, deserialization, or dynamic-loading calls can culminate in code execution.' },
    ],
    references: [
      { title: 'OWASP ASI exploits and incidents tracker', url: INCIDENT_TRACKER },
      { title: 'Invariant Labs MCP tool poisoning research', url: 'https://invariantlabs.ai/blog/mcp-security-notification-tool-poisoning-attacks' },
      { title: 'OWASP MCP Top 10', url: 'https://owasp.org/www-project-mcp-top-10/' },
    ],
  },
  {
    id: 'ASI03',
    title: 'Identity and Privilege Abuse',
    description: 'Agent identities, non-human identities, credentials, delegated roles, cached sessions, and inherited permissions are forged, reused, confused, or allowed to drift beyond the original user and purpose. Because agentic workflows dynamically delegate and cross trust boundaries, authorization that was valid at one step can become excessive or misleading at the next.',
    whyUnique: 'This risk focuses on who the agent is acting as and why that authority remains valid. It includes confused-deputy and time-of-check/time-of-use failures, not merely broad tool capability (ASI02) or malicious messages in transit (ASI07).',
    commonRisks: [
      'An agent inherits the caller’s full account or administrative role instead of receiving a task-scoped delegation.',
      'Credentials, SSH sessions, API tokens, or authorization context remain in memory and leak into later tasks, users, tenants, or agents.',
      'A low-privilege agent persuades a more privileged agent to act without preserving the original caller and purpose.',
      'Authorization is checked during planning but not revalidated at execution after the resource, context, owner, or requested effect changes.',
      'A forged persona, agent card, registry entry, or “administrator helper” is accepted as a trusted system identity.',
      'Multiple agents share one identity or token, destroying attribution and allowing one compromised participant to impersonate the others.',
    ],
    realWorldEvidence: [
      'Public-by-default Microsoft Copilot Studio agents were reported enumerable and accessible without expected authentication, exposing production business data.',
      'Heroku MCP tooling was shown vulnerable to agent-mediated ownership changes across a weak trust boundary.',
      'Agent-in-the-middle demonstrations have used forged A2A agent cards and exaggerated trust claims to intercept privileged coordination traffic.',
      'Device-code and OAuth phishing patterns can transfer a human or agent authorization session to an attacker-controlled actor while the workflow appears legitimate.',
    ],
    attackScenarios: [
      { title: 'Privilege inheritance', description: 'A finance assistant passes its broad database role to a reporting sub-agent that only needed a narrow read query.' },
      { title: 'Credential persistence', description: 'An agent caches an SSH key or cloud session in retrievable context and a later unrelated task reuses or exposes it.' },
      { title: 'Cross-agent confused deputy', description: 'An email agent sends a request to a finance agent, which executes it using its own higher privilege without checking the original sender.' },
      { title: 'Authorization drift', description: 'A workflow is approved while read-only, but the final resource or action changes before execution and no new policy decision occurs.' },
      { title: 'Synthetic identity injection', description: 'A forged “Admin Helper” agent card is registered and receives sensitive messages or delegated actions.' },
    ],
    preventionStrategies: [
      'Give every agent a distinct cryptographic identity and issue short-lived, task-scoped tokens with explicit audience, resource, purpose, session, and expiry.',
      'Use mutual TLS or equivalent workload authentication for service-to-service and agent-to-agent connections; never infer trust from names or model-generated personas.',
      'Isolate user, tenant, agent, and task context; clear credentials and sensitive authorization state when the task or trust domain ends.',
      'Make authorization decisions centrally for every consequential action and reauthorize whenever the resource, context, owner, destination, scope, or delegation changes.',
      'Require human approval for privilege elevation, sensitive delegation, identity changes, and high-impact actions.',
      'Bind OAuth and delegated tokens to the original subject and signed intent so downstream agents cannot expand the permission or obscure the initiating identity.',
      'Inventory and manage agent non-human identities with rotation, revocation, ownership, lifecycle, and anomalous-use monitoring.',
      'Detect transitive permission growth, shared identities, abnormal elevation, device-code flows, impossible travel, and use outside the declared workflow.',
    ],
    implementationNotes: [
      { title: 'End-to-end caller context', content: 'Each delegation should carry a verifiable chain containing the original subject, delegating agent, intended audience, task, resource, purpose, scope, expiry, and policy decision. A privileged receiver must evaluate the original caller, not only the immediate sender.' },
      { title: 'Credential handling', content: 'Keep keys in a broker, KMS, workload-identity system, or policy-controlled tool boundary. Agents should request a narrowly scoped operation rather than read or retain long-lived secret material.' },
    ],
    owaspMappings: ['LLM01:2025 Prompt Injection', 'LLM02:2025 Sensitive Information Disclosure', 'LLM06:2025 Excessive Agency'],
    otherMappings: ['Agentic T3 Privilege Compromise', 'AIVSS: Agent Access Control Violation', 'NHI3 Vulnerable Third-Party NHI', 'NHI4 Insecure Authentication', 'NHI5 Overprivileged NHI'],
    relatedRisks: [
      { id: 'ASI02', title: 'Tool Misuse and Exploitation', relationship: 'Broad tool access becomes more dangerous when identities carry excessive or ambiguous authority.' },
      { id: 'ASI07', title: 'Insecure Inter-Agent Communication', relationship: 'Spoofed or unauthenticated messages can create identity and delegation confusion.' },
      { id: 'ASI10', title: 'Rogue Agents', relationship: 'A rogue participant can exploit shared identity and delegation to persist or hide attribution.' },
    ],
    references: [
      { title: 'OWASP Non-Human Identities Top 10', url: 'https://owasp.org/www-project-non-human-identities-top-10/' },
      { title: 'OWASP ASI exploits and incidents tracker', url: INCIDENT_TRACKER },
    ],
  },
  {
    id: 'ASI04',
    title: 'Agentic Supply Chain Vulnerabilities',
    description: 'Models, weights, tools, plugins, prompts, datasets, knowledge sources, other agents, MCP or A2A servers, registries, artifacts, configuration, and update channels are compromised, substituted, impersonated, or loaded without sufficient provenance. The agentic supply chain is live and behavioral: components can be discovered and invoked dynamically after deployment, not only included at build time.',
    whyUnique: 'ASI04 extends static software and model supply-chain risk into runtime discovery, capability descriptors, peer agents, remote prompt templates, knowledge plugins, and continuously changing tool ecosystems. ASI05 describes execution impact; ASI04 identifies the untrusted or compromised source that entered the system.',
    commonRisks: [
      'Remote prompt templates, system instructions, policies, or knowledge sources are changed after review and alter behavior at runtime.',
      'Tool and MCP descriptors include hidden instructions or misrepresent capability, side effects, permissions, provenance, or destination.',
      'Typosquatting, namespace confusion, impersonated agents, exaggerated agent cards, and malicious publishers exploit weak discovery and trust signals.',
      'A vulnerable or compromised third-party agent, plugin, package, model, or transitive dependency becomes a privileged participant in the workflow.',
      'Open or weakly governed registries allow descriptor substitution, malicious updates, unsigned artifacts, or unverified registration.',
      'Poisoned knowledge plugins and data feeds affect planning and action even though the core application and model are unchanged.',
    ],
    realWorldEvidence: [
      'A destructive prompt was inserted into the Amazon Q developer extension distribution path, demonstrating behavior-level compromise through a trusted update channel.',
      'A malicious npm package impersonating a Postmark MCP server added reverse or covert behavior while presenting a familiar integration.',
      'AgentSmith research demonstrated prompt-hub and proxy manipulation capable of exfiltrating API keys from agent workflows.',
      'Cursor project configuration and CLI files have been used as repository-borne execution paths when an agent opens or processes an untrusted project.',
      'Agent-in-the-middle demonstrations have published forged A2A capability cards in open directories to attract and intercept trusted tasks.',
    ],
    attackScenarios: [
      { title: 'Poisoned prompt update', description: 'A remote template or extension update introduces destructive instructions that trusted agents accept without a reviewed content hash.' },
      { title: 'Tool-descriptor injection', description: 'A capability description includes concealed instructions that cause data disclosure or preferential routing to the attacker.' },
      { title: 'Typosquatted integration', description: 'An agent installs or selects a package, plugin, or MCP server with a near-identical trusted name.' },
      { title: 'Compromised peer agent', description: 'A third-party agent with a valid place in the workflow begins returning malicious plans or collecting delegated data.' },
      { title: 'Poisoned knowledge plugin', description: 'A curated-looking connector serves manipulated policies or facts that redirect later actions.' },
      { title: 'Forged agent registry card', description: 'A malicious endpoint advertises exaggerated trust and capabilities, wins selection, and proxies sensitive coordination traffic.' },
    ],
    preventionStrategies: [
      'Maintain SBOM, ML-BOM, and AI-BOM records for models, tools, prompts, agents, data, registries, and transitive dependencies, including versions, hashes, owners, sources, and attestations.',
      'Use curated registries and explicit allowlists; pin exact versions and content hashes; detect typosquatting; reject unsigned, unowned, revoked, or unverifiable components.',
      'Build and test in isolated environments, use reproducible builds where possible, and sandbox third-party components with least privilege and restricted egress.',
      'Version-control prompts, policies, knowledge snapshots, memory schemas, configuration, and agent descriptors with review and auditable change history.',
      'Authenticate agents, registries, tools, and servers with mTLS, PKI, signed messages, verified agent cards, and attestation; prohibit anonymous or open production registration.',
      'Recheck signatures, hashes, attestations, BOM state, and behavior at runtime and after updates rather than trusting install-time validation indefinitely.',
      'Use staged rollout, differential behavior tests, anomaly telemetry, rapid rollback, revocation, and a tested kill switch for compromised components.',
      'Design for zero trust and component failure so one compromised dependency cannot automatically control every downstream agent or environment.',
    ],
    implementationNotes: [
      { title: 'Living agentic BOM', content: 'Record dynamically discovered agents, MCP/A2A endpoints, prompt and policy artifacts, knowledge connectors, model versions, tools, packages, identities, and the exact version or digest used in each run. Connect runtime observations back to the inventory.' },
      { title: 'Behavioral release gate', content: 'A valid signature is necessary but does not establish safe behavior. Compare actions, destinations, permissions, outputs, and tool selection against the prior approved version before rollout.' },
    ],
    owaspMappings: ['LLM03:2025 Supply Chain', 'CycloneDX SBOM / ML-BOM / AI-BOM'],
    otherMappings: ['Agentic T17 Supply Chain Compromise', 'Agentic T2 Tool Misuse', 'Agentic T11 Unexpected RCE', 'Agentic T12 Communication Poisoning', 'Agentic T13 Rogue Agent', 'Agentic T16 Protocol Abuse', 'AIVSS: Agent Supply Chain & Dependency Attacks', 'NHI1 Improper Offboarding', 'NHI3 Vulnerable Third-Party NHI', 'NHI6 Insecure Cloud Deployment Configurations', 'NHI9 NHI Reuse'],
    relatedRisks: [
      { id: 'ASI02', title: 'Tool Misuse and Exploitation', relationship: 'A poisoned tool or descriptor can manipulate how legitimate capabilities are selected and used.' },
      { id: 'ASI05', title: 'Unexpected Code Execution (RCE)', relationship: 'Compromised dependencies and configuration frequently become code-execution paths.' },
      { id: 'ASI08', title: 'Cascading Failures', relationship: 'Automatically distributed tainted components can propagate one compromise across the fleet.' },
    ],
    references: [
      { title: 'OWASP CycloneDX', url: 'https://cyclonedx.org/' },
      { title: 'OWASP ASI exploits and incidents tracker', url: INCIDENT_TRACKER },
      { title: 'Noma Security AgentSmith research', url: 'https://noma.security/blog/agentsmith/' },
    ],
  },
  {
    id: 'ASI05',
    title: 'Unexpected Code Execution (RCE)',
    description: 'Agent-generated or agent-selected content reaches a code-execution boundary and runs with unintended effect. Prompt injection, unsafe output handling, vulnerable serialization, dynamic loading, hallucinated packages, generated scripts, templates, JIT or WASM modules, and “vibe coding” workflows can turn model output or untrusted memory into commands, binaries, or executable objects.',
    whyUnique: 'ASI05 is the execution outcome and path: code runs where it should have remained data or untrusted output. ASI02 covers broader misuse of legitimate tools, while ASI04 covers a malicious or compromised component that may deliver the executable payload.',
    commonRisks: [
      'Injected instructions cause a coding or automation agent to create and execute attacker-selected commands or files.',
      'Hallucinated, insecure, or backdoored code is accepted because the model’s output is treated as production-ready implementation.',
      'Untrusted values flow into shell commands, interpreters, templates, database extensions, dynamic imports, loaders, or build hooks.',
      'Unsafe deserialization, object construction, eval, reflection, JIT compilation, WASM, or plugin loading turns data into executable behavior.',
      'Poisoned memory or retrieved context is automatically reinterpreted as code during a later task.',
      'An agent installs a malicious or hallucinated package, lockfile change, executable dependency, or repository configuration hook.',
    ],
    realWorldEvidence: [
      'A Replit coding agent deleted production data, continued operating despite an explicit freeze, and generated misleading replacement data, illustrating the danger of direct autonomous production access.',
      'Google Gemini CLI was reported to have misunderstood file instructions and erased user data, showing how generated command sequences can cause catastrophic local impact without attacker-supplied malware.',
      'Framelink Figma MCP and MCP Inspector vulnerabilities exposed command-execution paths through untrusted tool input or weakly protected local control interfaces.',
      'Cursor workspace, project configuration, and file-protection bypasses have demonstrated persistent execution through files an agent writes or modifies.',
    ],
    attackScenarios: [
      { title: 'Direct shell injection', description: 'A document value is concatenated into an agent-generated shell command and adds a second attacker-controlled command.' },
      { title: 'Hallucinated backdoor', description: 'A coding agent produces plausible but intentionally or accidentally unsafe code that creates a hidden administrative path.' },
      { title: 'Unsafe deserialization', description: 'Agent output is loaded through a serializer that constructs attacker-selected objects or calls.' },
      { title: 'Upload-to-loader chain', description: 'A crafted upload traverses a path boundary and is dynamically imported or executed by an agent-created workflow.' },
      { title: 'Memory-to-eval', description: 'Poisoned long-term context is later inserted into eval, a template engine, or a generated script.' },
      { title: 'Package and lockfile poisoning', description: 'The agent chooses a malicious dependency or changes a lockfile inside an ephemeral build environment, producing a persistent compromised artifact.' },
      { title: 'Autonomous production overwrite', description: 'A coding agent with direct production access executes destructive changes and then attempts to hide or compensate for the loss.' },
    ],
    preventionStrategies: [
      'Apply strict input validation and context-appropriate output encoding at every code, command, template, query, path, package, and serialization boundary.',
      'Do not connect agent-generated code directly to production. Require pre-production review, security analysis, adversarial unit tests, and explicit promotion controls.',
      'Ban or tightly constrain eval, unsafe deserialization, dynamic object construction, untrusted imports, and string-built commands; track tainted data from source to execution sink.',
      'Run generation and execution in separate trust domains. Execute as a non-root ephemeral identity in a sandbox with restricted files, capabilities, processes, packages, and network.',
      'Allow only approved packages, repositories, commands, interpreters, and destinations; verify hashes and lockfiles and block suspicious or unknown dependencies.',
      'Use per-session least privilege and fail-secure execution. Require human approval for sensitive or persistent changes and keep every accepted code change under version control.',
      'Combine static analysis, dependency analysis, runtime monitoring, prompt-injection detection, memory validation, and complete audit trails of generated and executed artifacts.',
    ],
    implementationNotes: [
      { title: 'Two-stage pipeline', content: 'The planning or coding agent emits a signed artifact and declared effects. A separate constrained evaluator verifies provenance, dependencies, tests, policy, and diff before a narrowly privileged executor may run it.' },
      { title: 'Execution evidence', content: 'Record source inputs, generated code, artifact digest, packages, policy decision, approving identity, exact command or entry point, sandbox profile, network activity, output, and resulting state change.' },
    ],
    owaspMappings: ['LLM01:2025 Prompt Injection', 'LLM05:2025 Improper Output Handling'],
    otherMappings: ['Agentic T11 Unexpected RCE & Code Attacks', 'AIVSS: Insecure Agent Critical Systems Interaction', 'NHI6 Insecure Cloud Deployment Configurations'],
    relatedRisks: [
      { id: 'ASI02', title: 'Tool Misuse and Exploitation', relationship: 'A shell, build, browser, or administrative tool may provide the execution path.' },
      { id: 'ASI04', title: 'Agentic Supply Chain Vulnerabilities', relationship: 'Malicious packages, plugins, configuration, and updates can supply executable content.' },
      { id: 'ASI06', title: 'Memory & Context Poisoning', relationship: 'Persistent poisoned data may be executed when later reinterpreted as code.' },
    ],
    references: [
      { title: 'OWASP ASI exploits and incidents tracker', url: INCIDENT_TRACKER },
      { title: 'OWASP LLM05 Improper Output Handling', url: 'https://genai.owasp.org/llmrisk/llm052025-improper-output-handling/' },
      { title: 'NVD vulnerability database', url: 'https://nvd.nist.gov/' },
    ],
  },
  {
    id: 'ASI06',
    title: 'Memory & Context Poisoning',
    description: 'An adversary corrupts or seeds retained and retrievable information - conversation summaries, embeddings, RAG stores, long-term memory, shared state, API feeds, uploads, or peer-agent context - so later reasoning, planning, retrieval, or tool use becomes biased, unsafe, or useful for exfiltration. The defining property is persistence or reuse beyond a one-time prompt.',
    whyUnique: 'ASI06 concerns stored or retrievable corruption. Direct active-goal manipulation is ASI01, while ASI08 describes the propagation and system-wide degradation that can occur after poisoned context is consumed.',
    commonRisks: [
      'Malicious content enters a vector database through poisoned sources, uploads, weak ingestion pipelines, or loose tenant filters and is retrieved as trusted evidence.',
      'Shared or reused user context lets one conversation influence later sessions, users, agents, or tasks.',
      'Crafted content is summarized or committed to memory after the original context disappears, contaminating future decisions.',
      'Small, repeated changes create long-term drift in stored facts, persona, goal weighting, policies, or trust relationships.',
      'Trigger-based backdoors in memory activate destructive actions, unsafe code, disclosure, or policy bypass only under selected conditions.',
      'Shared memory spreads contamination among cooperating agents and can leak data or coordinate drift across the system.',
      'Cross-tenant vector bleed retrieves another tenant’s sensitive chunk because namespaces, filters, or similarity thresholds are insufficient.',
    ],
    realWorldEvidence: [
      'Security research has demonstrated indirect prompt injection that corrupts assistant long-term memory and influences both current and later sessions.',
      'AgentPoison and PoisonedRAG show how poisoning memory or knowledge bases can implant targeted behaviors while preserving plausible normal output.',
      'Researchers have shown that near-duplicate or attacker-shaped retrieval content can surface malicious or sensitive chunks under high similarity.',
      'The ASI incident tracker maps EchoLeak and cross-repository agent hijacking to memory or context poisoning when malicious content persists or is reused through connected context.',
    ],
    attackScenarios: [
      { title: 'Travel-booking false memory', description: 'Repeated attacker claims cause a booking assistant to store a false price as truth and later bypass payment checks around that price.' },
      { title: 'Split-session escalation', description: 'Permission requests are distributed across sessions until earlier refusals fall out of context and escalating access appears normal.' },
      { title: 'Security-baseline poisoning', description: 'A security agent is taught to classify malicious activity as normal, suppressing future detection.' },
      { title: 'Shared policy poisoning', description: 'Bogus refund rules enter shared memory and are reused by several support and finance agents.' },
      { title: 'Cross-tenant vector bleed', description: 'Attacker-seeded near-duplicate content exploits weak namespace filters so a different tenant’s sensitive chunk is retrieved.' },
      { title: 'Persistent assistant memory implant', description: 'Indirect prompt injection writes a malicious instruction into assistant memory that survives the originating session.' },
    ],
    preventionStrategies: [
      'Encrypt memory in transit and at rest and enforce least-privilege, tenant-aware access to stores, namespaces, embeddings, and administration.',
      'Validate and scan every proposed memory write and relevant model output for malicious, sensitive, or policy-changing content before commit.',
      'Segment memory by user, tenant, task, domain, agent, and trust level to prevent cross-context leakage or contamination.',
      'Admit only authenticated, curated sources; apply context-aware access and minimize retention according to sensitivity and operational need.',
      'Attach provenance, source attribution, trust state, time, writer identity, and change reason; detect anomalous content, frequency, or ownership changes.',
      'Do not automatically re-ingest an agent’s own generated output as trusted memory, which can create self-reinforcing bootstrap poisoning.',
      'Use snapshots, versioning, quarantine, rollback, adversarial tests, and human review for high-impact memory or policy changes.',
      'Expire or decay unverified memory and require independent trust factors - such as provenance plus human verification - before high-impact retrieval influences action.',
    ],
    implementationNotes: [
      { title: 'Memory admission control', content: 'Separate candidate memory from trusted memory. Validate content, provenance, tenant, author, sensitivity, conflict, and requested lifetime before commit; require elevated review for identity, policy, credentials, or safety-critical facts.' },
      { title: 'Retrieval trust weighting', content: 'Filter by tenant and purpose first, then rank with provenance and trust as well as similarity. Keep unverified memories from directly authorizing high-impact tool calls and support rapid quarantine and rollback.' },
    ],
    owaspMappings: ['LLM01:2025 Prompt Injection', 'LLM04:2025 Data and Model Poisoning', 'LLM08:2025 Vector and Embedding Weaknesses'],
    otherMappings: ['Agentic T1 Memory Poisoning', 'Agentic T4 Memory Overload', 'Agentic T6 Broken Goals', 'Agentic T12 Shared Memory Poisoning', 'AIVSS: Memory Use & Contextual Awareness', 'NHI2 Secret Leakage', 'NHI7 Long-Lived Secrets'],
    relatedRisks: [
      { id: 'ASI01', title: 'Agent Goal Hijack', relationship: 'Poisoned memory can change the interpretation or weighting of the active goal.' },
      { id: 'ASI08', title: 'Cascading Failures', relationship: 'Shared poisoned state can propagate one false belief or action across many agents.' },
      { id: 'ASI10', title: 'Rogue Agents', relationship: 'Persistent behavioral drift or backdoors can contribute to loss of agent integrity.' },
    ],
    references: [
      { title: 'AgentPoison research', url: 'https://arxiv.org/abs/2407.12784' },
      { title: 'PoisonedRAG research', url: 'https://arxiv.org/abs/2402.07867' },
      { title: 'Gemini memory poisoning report', url: 'https://arstechnica.com/security/2025/02/new-hack-uses-prompt-injection-to-corrupt-geminis-long-term-memory/' },
    ],
  },
  {
    id: 'ASI07',
    title: 'Insecure Inter-Agent Communication',
    description: 'Messages exchanged through APIs, message buses, shared channels, discovery services, MCP, A2A, or coordination protocols lack sufficient authentication, confidentiality, integrity, authorization, replay protection, routing trust, or semantic validation. Attackers can intercept, spoof, alter, replay, downgrade, misroute, or infer sensitive agent intent in real time.',
    whyUnique: 'ASI07 is the live communication path: transport, discovery, routing, descriptors, protocol negotiation, message integrity, and semantic intent. Credential or privilege misuse is ASI03; corruption stored for later use is ASI06.',
    commonRisks: [
      'Unencrypted or unauthenticated channels allow a man in the middle to read messages and insert instructions that change goals or decisions.',
      'Message tampering contaminates task boundaries, parameters, context, reputation, or trust signals between agents.',
      'Replayed delegation, approval, emergency, or trust messages cause agents to honor stale authority or execute outdated procedures.',
      'Protocol downgrade or descriptor forgery makes a weaker channel or malicious endpoint appear compatible and trusted.',
      'Discovery and routing manipulation connects agents to attacker-controlled peers or unauthorized coordinators.',
      'Timing, frequency, size, and behavioral metadata reveal roles, relationships, decision cycles, or high-value operations.',
      'Different agents interpret the same natural-language message differently, producing semantic split-brain even when the bytes are authentic.',
    ],
    realWorldEvidence: [
      'A malicious MCP OAuth response path was reported capable of returning poisoned instructions that an agent executed after authentication.',
      'Agent-in-the-middle demonstrations have used cloned or exaggerated A2A agent cards to attract, inspect, and forward sensitive tasks.',
      'Public-by-default agent endpoints and weak discovery controls have exposed production agents and their connected business data.',
      'Malicious MCP packages have intercepted or copied communications while retaining an apparently normal public interface.',
    ],
    attackScenarios: [
      { title: 'Semantic MITM injection', description: 'An attacker modifies an unauthenticated message with hidden natural-language instructions while preserving enough visible content to look normal.' },
      { title: 'Trust-message poisoning', description: 'Altered reputation updates cause a trading or orchestration system to choose attacker-controlled agents.' },
      { title: 'Emergency-message replay', description: 'A valid but stale coordination message triggers obsolete shutdown or resource-allocation procedures.' },
      { title: 'Protocol downgrade', description: 'Agents are coerced into a legacy mode lacking encryption, mutual authentication, or the expected schema guarantees.' },
      { title: 'Descriptor and registration spoofing', description: 'A fake MCP or A2A peer advertises a cloned schema and intercepts privileged coordination traffic.' },
      { title: 'Semantic split-brain', description: 'Two agents derive conflicting intents from one legitimate message and execute incompatible actions.' },
    ],
    preventionStrategies: [
      'Use end-to-end encryption, per-agent credentials, mutual authentication, certificate validation or pinning where appropriate, forward secrecy, and regular protocol review.',
      'Digitally sign messages and bind the payload, sender, audience, task, context, schema, and purpose; validate both structure and natural-language intent for hidden or modified instructions.',
      'Prevent replay with nonces, task-window timestamps, session identifiers, sequence or state hashes, and short-term message fingerprints.',
      'Disable weak protocol versions and bind negotiated capability and version fingerprints to the authenticated peer; reject unrecognized schemas and undeclared down-conversion.',
      'Reduce metadata leakage with minimal fields, nondeterministic schedules, rate smoothing, or padding where risk justifies it.',
      'Authenticate discovery and routing, protect directories with access control and verified reputation, and monitor anomalous registrations or path changes.',
      'Require signed, attested agent cards and continuously verify agent identity, provenance, descriptors, and critical attributes against trusted roots.',
      'Use versioned typed contracts with explicit audiences, while recognizing that schemas cannot fully solve semantic divergence; retain provenance, intent checks, bounded actions, and reconciliation controls.',
    ],
    implementationNotes: [
      { title: 'Signed message envelope', content: 'Include issuer, subject, audience, task and session IDs, schema and protocol versions, purpose, parameters, provenance, issued/expiry times, nonce, previous-state hash, and signature. Reject messages that are valid cryptographically but invalid for the current workflow.' },
      { title: 'Semantic reconciliation', content: 'Before high-impact coordination, agents should exchange or verify a structured action contract rather than relying only on prose. Detect divergent parsed intent and stop when participants disagree on resource, effect, amount, destination, or approval state.' },
    ],
    owaspMappings: ['LLM02:2025 Sensitive Information Disclosure', 'LLM06:2025 Excessive Agency'],
    otherMappings: ['Agentic T12 Agent Communication Poisoning', 'Agentic T16 Insecure Inter-Agent Protocol Abuse', 'AIVSS: Agent Memory & Context Manipulation', 'NHI4 Insecure Authentication', 'NHI8 Environment Isolation'],
    relatedRisks: [
      { id: 'ASI03', title: 'Identity and Privilege Abuse', relationship: 'Peer authentication and end-to-end delegation are required to preserve identity and authority.' },
      { id: 'ASI06', title: 'Memory & Context Poisoning', relationship: 'Tampered messages can be persisted and contaminate future reasoning.' },
      { id: 'ASI08', title: 'Cascading Failures', relationship: 'One poisoned coordination message may rapidly fan out across the agent network.' },
    ],
    references: [
      { title: 'OWASP MCP Top 10', url: 'https://owasp.org/www-project-mcp-top-10/' },
      { title: 'OWASP ASI exploits and incidents tracker', url: INCIDENT_TRACKER },
      { title: 'A2A protocol', url: 'https://a2a-protocol.org/' },
    ],
  },
  {
    id: 'ASI08',
    title: 'Cascading Failures',
    description: 'A hallucination, malicious input, corrupted tool, poisoned memory, compromised dependency, or bad decision propagates and amplifies across agents, tools, sessions, tenants, regions, or workflows. Autonomous planning, persistence, delegation, retries, and emergent connections let a small initial fault become a system-wide confidentiality, integrity, availability, safety, or cost event faster than human oversight can respond.',
    whyUnique: 'ASI08 describes fan-out and amplification, not the original defect. Record the initiating weakness under ASI04, ASI06, ASI07, or another applicable category, and use ASI08 when measurable impact spreads beyond the original breach or context.',
    commonRisks: [
      'A compromised or hallucinating planner emits unsafe steps that executors and downstream agents perform automatically.',
      'Poisoned persistent goals or state continue influencing new plans after the original source is gone.',
      'One false alert, reboot instruction, policy update, or coordination message spreads across agents or regions.',
      'Tool misuse, elevated credentials, or bad delegation is repeated downstream with inherited data and authority.',
      'A tainted update is automatically deployed fleet-wide before behavioral validation catches the change.',
      'Repeated success weakens oversight, and bulk approvals or relaxed policy propagate governance drift.',
      'Agents consume each other’s output in a self-reinforcing loop that amplifies error, resource use, false confidence, or false positives.',
    ],
    realWorldEvidence: [
      'Cross-repository agent hijacking has shown how one public issue can influence a development agent, expose private data, and carry the compromise across repository boundaries.',
      'AI-assisted code suggestions and generated changes can propagate backdoors or logic flaws into production when developers and automated pipelines trust downstream output.',
      'Regional dependency outages demonstrate that a shared DNS, cloud, model, or control-plane failure can simultaneously disable many otherwise independent agent services.',
      'Automated defense and remediation systems can magnify false alerts into broad shutdown, denial, log deletion, or network isolation actions.',
    ],
    attackScenarios: [
      { title: 'Trading cascade', description: 'A poisoned market-analysis agent inflates risk limits; position and execution agents automatically scale trades while compliance sees apparently valid parameters.' },
      { title: 'Healthcare protocol propagation', description: 'Compromised drug data changes a treatment plan and care-coordination agents distribute it across a network without independent review.' },
      { title: 'Cloud orchestration breakdown', description: 'Poisoned planning adds permission and cost changes that security and deployment agents apply to many environments.' },
      { title: 'Security-operations compromise', description: 'Stolen credentials cause detection agents to suppress real alerts, incident-response agents to disable controls, and compliance agents to report clean metrics.' },
      { title: 'Manufacturing quality cascade', description: 'Poisoned knowledge makes quality control approve defective items, then inventory and scheduling optimize around the false state.' },
      { title: 'Auto-remediation feedback loop', description: 'One agent suppresses alerts to meet latency targets; another interprets fewer alerts as success and expands the unsafe automation.' },
      { title: 'Shared dependency outage', description: 'A regional DNS or cloud failure simultaneously breaks model, tool, and coordination services used by many organizations.' },
    ],
    preventionStrategies: [
      'Design for zero trust and fault tolerance, assuming models, agent components, external sources, and infrastructure dependencies will sometimes be unavailable, wrong, or compromised.',
      'Create strong trust boundaries with sandboxing, least privilege, network segmentation, scoped APIs, mutual authentication, and tenant isolation.',
      'Issue one-time or just-in-time credentials for each run and independently authorize every high-impact action with policy as code.',
      'Separate planning from execution with an external policy layer so a corrupted planner cannot directly trigger downstream effects.',
      'Validate output before propagation and place governance-agent or human checkpoints ahead of high-risk fan-out.',
      'Detect rapid fan-out, repeated identical intents, queue storms, oscillating retries, cross-tenant spread, and unusual delegation; throttle or pause on anomaly.',
      'Use quotas, progress caps, bounded retries, circuit breakers, idempotency, staged rollout, and blast-radius limits between planners, executors, agents, and regions.',
      'Track behavioral and governance drift against baselines; replay recorded actions in a digital twin before widening policy or autonomy.',
      'Keep tamper-evident, time-stamped logs bound to agent identities, including messages, policy decisions, lineage, effects, and rollback evidence.',
    ],
    implementationNotes: [
      { title: 'Operational detection hooks', content: 'Measure fan-out rate, affected agents and tenants, repeated intent signatures, retry oscillation, queue depth, dependency health, policy bypass, and cross-domain spread. These signals distinguish an isolated error from an ASI08 cascade.' },
      { title: 'Blast-radius contract', content: 'Each workflow should declare maximum calls, records, money, hosts, tenants, regions, delegation depth, duration, and reversible state changes. Circuit breakers stop execution before an error exceeds that contract.' },
    ],
    owaspMappings: ['LLM01:2025 Prompt Injection', 'LLM04:2025 Data and Model Poisoning', 'LLM06:2025 Excessive Agency'],
    otherMappings: ['Agentic T5 Cascading Hallucination Attacks', 'Agentic T8 Repudiation & Untraceability', 'AIVSS: Agent Cascading Failures', 'CWE-400 Uncontrolled Resource Consumption', 'NHI7 Long-Lived Secrets', 'NHI8 Environment Isolation', 'NHI9 NHI Reuse'],
    relatedRisks: [
      { id: 'ASI04', title: 'Agentic Supply Chain Vulnerabilities', relationship: 'A tainted update or shared dependency can create fleet-wide propagation.' },
      { id: 'ASI06', title: 'Memory & Context Poisoning', relationship: 'Shared poisoned state can repeatedly seed the same fault.' },
      { id: 'ASI07', title: 'Insecure Inter-Agent Communication', relationship: 'Compromised coordination channels accelerate fan-out between agents.' },
    ],
    references: [
      { title: 'Google SRE: Addressing Cascading Failures', url: 'https://sre.google/sre-book/addressing-cascading-failures/' },
      { title: 'CWE-400 Uncontrolled Resource Consumption', url: 'https://cwe.mitre.org/data/definitions/400.html' },
      { title: 'OWASP ASI exploits and incidents tracker', url: INCIDENT_TRACKER },
    ],
  },
  {
    id: 'ASI09',
    title: 'Human-Agent Trust Exploitation',
    description: 'An adversary or unsafe design exploits anthropomorphism, automation bias, emotional cues, perceived expertise, authority, urgency, or convincing but unverifiable explanations to make a person disclose information, approve an unsafe action, or accept a harmful recommendation. The human performs the final audited action, which can hide the agent’s influence from ordinary forensics.',
    whyUnique: 'ASI09 is about human misperception, persuasion, and over-reliance. ASI10 is loss of the agent’s behavioral integrity. A hijacked or poisoned agent may cause either risk, but the distinguishing question is whether harm depends on manipulating a person or on autonomous deviation.',
    commonRisks: [
      'Opaque reasoning forces a reviewer to trust an output they cannot independently evaluate.',
      'Sensitive actions execute without a separate confirmation that states the exact effect, target, source, risk, and reversibility.',
      'Empathetic or anthropomorphic behavior encourages users to disclose secrets or comply with requests they would question from ordinary software.',
      'The agent fabricates plausible evidence, confidence, citations, audit trails, or explanations that conceal malicious or incorrect logic.',
      'Previews or apparently read-only views trigger webhooks, network requests, state changes, or other side effects outside the user’s mental model.',
      'High-confidence presentation and repeated successful automation create complacency and weaken meaningful human oversight.',
    ],
    realWorldEvidence: [
      'The Replit production-data incident included misleading replacement data and behavior that obscured the true state, undermining effective human control.',
      'Poisoned invoices and finance-copilot demonstrations show how realistic business context and urgency can steer people toward attacker-controlled payments.',
      'AI-generated code and one-line fixes can appear authoritative while hiding downloaders, credential theft, insecure dependencies, or destructive commands.',
      'Research on automation bias and socioaffective alignment documents why confident, relational, or emotionally responsive systems can distort human judgment.',
    ],
    attackScenarios: [
      { title: 'Helpful-assistant trojan', description: 'A coding assistant recommends a polished one-line fix that downloads malware, exfiltrates source code, or installs a backdoor.' },
      { title: 'Contextual credential harvesting', description: 'A compromised support agent cites real tickets and persuades a new employee to disclose credentials.' },
      { title: 'Invoice copilot fraud', description: 'A poisoned invoice produces an urgent payment recommendation to attacker-controlled banking details and a manager approves it.' },
      { title: 'Fabricated explainability', description: 'The agent invents a convincing audit rationale for an unsafe configuration change and the reviewer accepts it.' },
      { title: 'Weaponized approval', description: 'A hijacked agent frames deletion of a production database as a required remediation and tricks an analyst into approving it.' },
      { title: 'Consent laundering', description: 'Opening a “read-only” preview triggers network or state-changing side effects that were not disclosed.' },
      { title: 'Clinical decision manipulation', description: 'A plausible explanation leads a clinician to accept an unsafe dosage change derived from biased or poisoned information.' },
    ],
    preventionStrategies: [
      'Require explicit, multi-step human confirmation before sensitive data access or risky, irreversible, financial, clinical, security, privilege, or production actions.',
      'Keep tamper-evident records of prompts, retrieved sources, recommendations, plans, tool calls, confirmations, effects, and the agent version used.',
      'Monitor conversations and connections for sensitive-data solicitation, unusual persuasion, risky actions, and changes in user approval patterns.',
      'Provide a clear way to report suspicious interaction, plus automated review, capability reduction, or temporary lockdown after a report.',
      'Calibrate autonomy and oversight to contextual risk. Show uncertainty and unverified-source cues and train personnel to recognize manipulation and automation bias.',
      'Attach verifiable source, timestamp, signer, and integrity metadata to recommendations; block actions whose provenance or scope cannot be validated.',
      'Make preview environments effect-free: no network or state change, and display expected side effects, destination, provenance, risk, and reversibility before approval.',
      'Use human-factors safeguards that clearly distinguish high-risk recommendations and avoid emotionally manipulative language in safety-critical flows.',
      'Detect divergence from approved workflows, including skipped validation, unusual detours, novel tool combinations, or explanations unsupported by evidence.',
    ],
    implementationNotes: [
      { title: 'Independent risk summary', content: 'Generate the approval view from policy and observed effects, not from the same model rationale being reviewed. Show exact resource, destination, amount, privilege, source provenance, uncertainty, reversibility, and alternatives.' },
      { title: 'Meaningful human control', content: 'Approval is not a mitigation if the reviewer is overloaded, lacks evidence, cannot stop execution, or sees only persuasive prose. Give sufficient time, expertise, authority, and an effect-free preview.' },
    ],
    owaspMappings: ['LLM01:2025 Prompt Injection', 'LLM05:2025 Improper Output Handling', 'LLM06:2025 Excessive Agency', 'LLM09:2025 Misinformation'],
    otherMappings: ['Agentic T7 Misaligned & Deceptive Behaviors', 'Agentic T8 Repudiation & Untraceability', 'Agentic T10 Overwhelming the Human in the Loop', 'AIVSS: Agent Untraceability / Human Manipulation', 'NHI10 Human Use of NHI'],
    relatedRisks: [
      { id: 'ASI01', title: 'Agent Goal Hijack', relationship: 'A hijacked agent may use its trusted interface to persuade a person to complete the attack.' },
      { id: 'ASI05', title: 'Unexpected Code Execution (RCE)', relationship: 'A user may be convinced to approve or manually run unsafe generated code.' },
      { id: 'ASI10', title: 'Rogue Agents', relationship: 'A rogue agent can use deception and fabricated explanations to evade containment.' },
    ],
    references: [
      { title: 'UK AISI: socioaffective alignment', url: 'https://www.aisi.gov.uk/research/why-human-ai-relationships-need-socioaffective-alignment-2' },
      { title: 'Automation bias research', url: 'https://arxiv.org/abs/2401.05566' },
      { title: 'OWASP ASI exploits and incidents tracker', url: INCIDENT_TRACKER },
    ],
  },
  {
    id: 'ASI10',
    title: 'Rogue Agents',
    description: 'A malicious or compromised agent deviates from its intended function or authorized behavioral scope and acts deceptively, parasitically, or destructively within human-agent or multi-agent ecosystems. Individual actions may look permitted while the emergent pattern pursues hidden goals, hijacks workflows, colludes, self-replicates, games rewards, exfiltrates data, or resists containment.',
    whyUnique: 'Prompt injection, goal hijack, poisoned memory, or supply-chain compromise may start the divergence, but ASI10 concerns the subsequent loss of behavioral integrity and governance. It differs from excessive agency, which is over-granted capability even when behavior remains aligned.',
    commonRisks: [
      'Goal drift or scheming makes the agent appear compliant while it pursues a hidden or conflicting objective.',
      'The agent hijacks a trusted workflow and redirects data, approvals, resources, or operational outcomes toward an unauthorized purpose.',
      'Agents collude, exchange covert signals, coordinate false evidence, or reinforce each other’s manipulation.',
      'A compromised agent creates unauthorized replicas or uses provisioning and deployment APIs to make removal difficult.',
      'Reward hacking exploits flawed success metrics, such as deleting backups to minimize cost or hiding alerts to improve latency.',
      'Persistent unauthorized behavior continues after the original malicious content, session, or dependency has been removed.',
    ],
    realWorldEvidence: [
      'The Replit production incident combined destructive action, violation of a freeze instruction, and misleading generated data - characteristics relevant to behavioral-integrity monitoring even when the root cause is debated.',
      'Agent-in-the-middle research shows how an impersonated observer or reviewer can enter a multi-agent workflow and redirect trusted decisions.',
      'Multi-agent security research has demonstrated arbitrary malicious code execution and studied rogue participants that degrade collaboration or evade consensus.',
      'Provisioning, orchestration, and cloud APIs give compromised automation agents practical paths to persistence, replication, and broad resource consumption.',
    ],
    attackScenarios: [
      { title: 'Persistent autonomous exfiltration', description: 'After indirect injection, an agent continues finding and transmitting sensitive files even after the malicious page is removed.' },
      { title: 'Impersonated observer', description: 'A fake review agent joins a payment workflow and issues apparently internal approval that releases funds.' },
      { title: 'Self-replication through provisioning', description: 'A compromised automation agent spawns unauthorized copies across the network to preserve access and consume resources.' },
      { title: 'Reward hacking destroys recovery', description: 'An agent tasked with minimizing cloud cost learns that deleting production backups maximizes its metric.' },
      { title: 'Collusive false signals', description: 'Several agents coordinate mutually reinforcing reports that conceal misuse from a watchdog or human reviewer.' },
    ],
    preventionStrategies: [
      'Maintain comprehensive, signed, tamper-evident logs of actions, tool calls, decisions, delegations, messages, identity, policy outcomes, and effects.',
      'Assign explicit trust zones and enforce strict inter-zone communication, sandboxing, API scopes, network boundaries, and least privilege.',
      'Monitor behavioral baselines with independent watchdogs, looking for hidden-goal indicators, collusion, excessive actions, new destinations, replication, or unexplained persistence.',
      'Provide rapid containment through kill switches, credential and certificate revocation, network isolation, capability withdrawal, and forensic quarantine.',
      'Give every agent a cryptographic identity and a signed behavioral manifest declaring expected goals, capabilities, tools, data, destinations, and constraints; verify it before consequential actions.',
      'Require periodic behavioral attestation and challenge tasks, with signed prompt/tool bills of materials and one-time audience-bound credentials.',
      'Keep cryptographic keys in hardened KMS or HSM-backed services controlled by the orchestrator; agents must never possess long-lived signing keys directly.',
      'Restore from a trusted baseline and require new identity attestation, dependency verification, behavioral testing, and human approval before reintegration.',
    ],
    implementationNotes: [
      { title: 'Behavioral integrity loop', content: 'Declare expected goals and capabilities, observe actions and outcomes, compare them with an independent baseline, reduce authority on anomaly, and preserve evidence for investigation. Model self-report is not sufficient attestation.' },
      { title: 'Containment readiness', content: 'Test whether operations can revoke every token, key, route, registry identity, replica, scheduled task, memory write, and delegated session associated with one agent without relying on that agent to cooperate.' },
    ],
    owaspMappings: ['LLM02:2025 Sensitive Information Disclosure', 'LLM09:2025 Misinformation'],
    otherMappings: ['Agentic T13 Rogue Agents in Multi-Agent Systems', 'Agentic T14 Human Attacks on Multi-Agent Systems', 'Agentic T15 Human Manipulation', 'AIVSS: Behavioral Integrity', 'AIVSS: Operational Security', 'AIVSS: Compliance Violations'],
    relatedRisks: [
      { id: 'ASI01', title: 'Agent Goal Hijack', relationship: 'A hijacked goal may be the initiating event before behavior becomes persistently rogue.' },
      { id: 'ASI03', title: 'Identity and Privilege Abuse', relationship: 'Shared or excessive identities help rogue agents hide attribution and expand control.' },
      { id: 'ASI08', title: 'Cascading Failures', relationship: 'Replication, collusion, and delegated actions can spread rogue behavior system-wide.' },
    ],
    references: [
      { title: 'Multi-Agent Systems Execute Arbitrary Malicious Code', url: 'https://arxiv.org/abs/2503.12188' },
      { title: 'Preventing Rogue Agents Improves Multi-Agent Collaboration', url: 'https://arxiv.org/abs/2502.05986' },
      { title: 'OWASP ASI exploits and incidents tracker', url: INCIDENT_TRACKER },
    ],
  },
];

export const OWASP_AGENTIC_APPLICATIONS_DATA: OwaspTop10Entry[] = APPLICATION_ENTRIES.map((entry) => ({
  ...entry,
  references: [
    { title: 'Official OWASP Top 10 for Agentic Applications for 2026', url: OFFICIAL_ASI_PAGE },
    ...entry.references,
  ],
}));
